name = "snapink"
compatibility_date = "2024-11-20"

# REQUIRED FOR PAGES
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "snapink_waitlist"
database_id = "9263527d-7f81-4277-a171-e20b364f918c"
